language: node_js
node_js:
  - 0.8
script:
  - "make test-ci"
install:
  - (cd /tmp && wget http://fallabs.com/kyotocabinet/pkg/kyotocabinet-1.2.76.tar.gz && tar xzf kyotocabinet-1.2.76.tar.gz && cd kyotocabinet-1.2.76 && sudo ./configure && sudo make && sudo make install && grep -q local /etc/ld.so.conf; if [ $? -ne 0 ]; then sudo echo "/usr/local/lib" >> /etc/ld.so.conf; sudo ldconfig; fi; exit 0)
  - npm install
notifications:
  email: false